### ISSUE TITLE
[bug] Markdown integration breaks dynamic commentstring on nightly

### ISSUE THREAD

**Issue by benlubas** [3rd/image.nvim#50] opened 2023-10-13 18:09 UTC
I use comment.nvim to comment code with a keybind. This uses treesitter to determine the correct comment string to use for files like markdown, where you could be in a code block, and need a different comment string.

I have no idea why, but enabling the markdown integration breaks this dynamic comment string functionality. So in a markdown file it would only even comment with html style comments, even in code blocks.

This only affects nightly

**Comment by jmbuhr** [comment] 2023-10-22 09:02
That's https://github.com/numToStr/Comment.nvim, right? I can reproduce this.

**Comment by jmbuhr** [comment] 2023-10-22 09:29
So, here is what I found out so far:

`Comment.nvim` get's the treesitter parser of the current buffer here https://github.com/numToStr/Comment.nvim/blob/0236521ea582747b58869cb72f70ccfa967d2e89/lua/Comment/ft.lua#L270
`vim.print(parser)` reveals that when `image.nvim` is disabled, the parser has injections (which it needs to find the correct language context for the commentstring), but when we enable it, the parser comes with:

`_injections_processed = false,`

And I have no idea why another plugin has an influence on `vim.treesitter.get_parser`.

**Comment by 3rd** [comment] 2023-10-22 09:33
Very weird that it does that. The parser is shared per-buffer, but it shouldn't have an impact on injections.
We just get the root and run a query on it :(

**Comment by jmbuhr** [comment] 2023-10-22 09:59
It's also weird because my plugin otter.nvim that provides the lsp features for injected languages also uses the parser and neither breaks itself nor breaks comments

**Comment by jmbuhr** [comment] 2023-10-22 10:29
My suspicion is that in image.nvim we are only getting the inline parser
```lua
    local parser = vim.treesitter.get_parser(buf, "markdown_inline")
```
and nvim.treesitter somehow caches this and remembers this for the current buffer.
Thus, when comment.nvim asks for the buffer: `local ok, parser = pcall(vim.treesitter.get_parser, A.nvim_get_current_buf())`, they get only the inline parser.
My plugin on the other hand explicitly specifies the language of the parser: https://github.com/jmbuhr/otter.nvim/blob/93227da6bc7db5c0e331df81dd92e91520e084de/lua/otter/keeper.lua#L207 and thus does not break.

So I think the fix is to explicitly get the parser language in `Comment.nvim` (with `vim.treesitter.language.get_lang()` for the current filetype instead of falling back to whatever parser was last created.

**Comment by 3rd** [comment] 2023-10-22 10:42
Super interesting, so it should work if it gets the parser after Comment.nvim.
Maybe it would work if we request the "markdown" parser first, then the inline one.

**Comment by jmbuhr** [comment] 2023-10-22 13:48
I tried that, but it then the query can't find the image node. Something is preventing the part in image.nvim from processing injections, and the inline parser is an injection into the block markdown parser.

**Comment by jmbuhr** [comment] 2023-10-22 13:48
This is all very weird

**Comment by benlubas** [comment] 2023-10-22 14:04
It might be worth it to bisect nightly versions as well. Would take a little bit but I suspect it would lead us right to the problem. Since it works on stable. 

Unfortunately I've completely broken my Linux install (first time :D) and am really busy this weekend so I can't do that myself for a little bit.

**Comment by jmbuhr** [comment] 2023-10-22 14:36
True, maybe it's a neovim issue.

**Comment by jmbuhr** [comment] 2023-10-22 14:52
So `get_parser` uses a table of parsers indexed by buffer number, meaning the first time a parser is being asked for for a buffer it is created and then reused. https://github.com/neovim/neovim/blob/master/runtime/lua/vim/treesitter.lua#L107

What this means in practice is that we can break other plugins when we attach a parser to a buffer that doesn't match the expected language associated with the filetype. So I believe the correct thing to do is actually change it here and don't require the "markdown_inline" parser but just the "markdown" parser. This will also require changing the way the query is handled, I'm not quite sure yet how to directly query a child-tree.

**Comment by 3rd** [comment] 2023-10-22 15:14
Awesome insight, thanks for researching. The behavior is very weird, wondering if it should be classified as a bug in Neovim. Anyhow, maybe we can work around this by not using the buffer parser, just getting its text and parsing it with markdown-inline separately.

**Comment by jmbuhr** [comment] 2023-10-22 15:17
I almost have the solution! PR soon :)

**Comment by jmbuhr** [comment] 2023-10-22 15:39
https://github.com/3rd/image.nvim/pull/58

**Comment by jmbuhr** [comment] 2023-10-22 15:53
Works now! :)

**Comment by 3rd** [comment] 2023-10-22 16:24
Fixed by https://github.com/3rd/image.nvim/pull/58 :tada:

**Closed by 3rd** 2023-10-22 16:24 UTC
