### ISSUE TITLE
Feature: Gif Support

### ISSUE THREAD

**Issue by DarkKronicle** [3rd/image.nvim#31] opened 2023-10-04 16:10 UTC
I don't know how feasible this would be (I haven't done too much neovim/lua dev), but I saw that ImageMagick has gif based functions. Would adding gif support be in the scope of this project? If this isn't, I'll see if I can get it working just by rendering each frame individually.

**Comment by 3rd** [comment] 2023-10-04 16:43
Hey, I think it's out of scope unless we find a way to reach acceptable performance.

I tried the render-one-frame-at-a-time approach and it's not great, because we have to move the cursor and restore it for each frame, and it's very visible: https://github.com/3rd/image.nvim/issues/17#issuecomment-1706664350

It would be possible for Kitty (https://sw.kovidgoyal.net/kitty/graphics-protocol/#animation) if implemented separately, but for now I'd like for things to work with ueberzugpp as well, many users don't use Kitty (which I think they should, it's the best in terms of features vs performance).

I'll continue to look into it, not just for rendering nyancat, but for building some sort of Canvas API (https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API). I just need to find a way to avoid moving the cursor, maybe through Kitty's remote API. If that works and we can have a generic rendering API with Kitty, I'll consider dropping ueberzugpp support.

**Closed by 3rd** 2023-10-04 16:43 UTC

**Comment by DarkKronicle** [comment] 2023-10-04 18:34
Alright, thanks for the quick response! I'll see if maybe I can get something working with Kitty.

**Comment by kovidgoyal** [comment] 2023-10-05 03:58
Not sure I understand the issue, but just in case the problem is kitty graphics commands moving the cursor, you can add C=1 to the graphics command to have the terminal not move the cursor.

**Comment by 3rd** [comment] 2023-10-05 07:52
Hey, thanks for chipping in!

We're using C=1, but it's not Kitty moving the cursor, it's us moving it to the right location where the image should be rendered, what the plugin does right now is:

1. Transmit the image
2. Move the cursor saving the initial position
3. Ask Kitty to render the image (ref by image id)
4. Restore the cursor position

It flickers when going through the frames because of the move/restore cycle, which is expected. It could work if it would be possible to specify the origin cell's x,y in the graphics payload instead of relying on the current cursor position, but I'm not sure what issues / complexities that would introduce.

**Comment by kovidgoyal** [comment] 2023-10-05 10:51
On Thu, Oct 05, 2023 at 12:52:38AM -0700, Andrei Neculaesei wrote:
> Hey, thanks for chipping in!
> 
> We're using C=1, but it's not Kitty moving the cursor, it's us moving it to the right location where the image should be rendered, what the plugin does right now is:
> 
> 1. Transmit the image
> 2. Move the cursor saving the initial position
> 3. Ask Kitty to render the image (ref by image id)
> 4. Restore the cursor position
> 
> It flickers when going through the frames because of the move/restore cycle, which is expected. It could work if it would be possible to specify the origin cell's x,y in the graphics payload instead of relying on the current cursor position, but I'm not sure what issues / complexities that would introduce.

I dont quite understand the source of this flickering? Are your wrapping
steps 2-4 in an atomic screen update escape sequence pair? If you are
there should be zero flickering, since the terminal emulator will do all
3 steps atomically.

**Comment by 3rd** [comment] 2023-10-07 11:14
Thank you! I was not aware of this capability, added now and it works wonderfully (but not through Tmux, looking into it).
